language: node_js
node_js:
  - "8"
script :
  - "npm build"
after_script:
  - "npm run test-nyc"

cache:
  directories:
  - node_modules

deploy:
  - provider: npm
    skip_cleanup: true
    email: heifade@126.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: heifade/check-string
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
