language: node_js
node_js:
  - "8"
script :
  - "npm test"
after_script:
  - "npm run test-nyc"

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  skip_cleanup: true
  email: heifade@126.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: heifade/check-string
